Fix compilation error: Remove remaining AlertDialog usage
- Remove showSplitScreenInstructions() method that was missed in cleanup
- This method was using AlertDialog.Builder but import was removed
- Method was not being called anywhere, safe to remove